require "user.core.options"
require "user.core.keymaps"
require "user.core.autocmds"

require "user.launch"

spec "user.core.treesitter"
spec "user.core.theme"
spec "user.core.lualine"
spec "user.core.indentline"
spec "user.core.whichkey"
spec "user.core.telescope"
spec "user.core.spectre"
spec "user.core.neotree"
spec "user.core.cmp"
spec "user.core.autopairs"
spec "user.core.comment"
spec "user.core.surround"
spec "user.core.conform"
spec "user.core.lint"
spec "user.core.schemastore"
spec "user.core.scrolleof"
spec "user.core.file-operations"
spec "user.core.devicons"

spec "user.lsp.mason"
spec "user.lsp.lspconfig"
spec "user.core.navic"

spec "user.extras.lsp.typescript-tools"
spec "user.extras.folding"
spec "user.extras.todo-comments"
spec "user.extras.project"
spec "user.extras.breadcrumbs"

spec "user.extras.dap"
spec "user.extras.nvim-jdtls"
spec "user.extras.neotest"

-- spec "user.extras.toggleterm"
spec "user.extras.hardtime"

spec "user.extras.harpoon"
-- spec "user.extras.copilot"
spec "user.extras.gopher"
spec "user.extras.highlight-colors"
spec "user.extras.scrolling"

require "user.lazy"
